### ISSUE TITLE
Job Advert!!!

### ISSUE THREAD

**Issue by kelleuseis** [edsml-dd1522/edsml-dd1522.github.io#1]
Hi！丁小朋友~ 我是字节跳动抖音数据产品线海外校招负责人Leo，我们产品线技术聚焦当前数据存储领域热点方向，分布式、大数据、数据库、高性能计算、数据灾备、容器、虚拟化、软硬件协同、DPU、操作系统等技术方向，致力于为智能世界构建最强数据基础设施，释放数据价值，点亮数字文明。 看了你的profile，我们产品线期待你的加入和共事。无论是软件开发、还是AI工程师、算法，岗位种类丰富且灵活~ 我们在全国一线城市都有Base地（上海、北京、杭州、南京、成都等）；也有12个实验室钻研前沿技术。我会内推您的简历，帮您尽快安排机考跟面试~ Leo（VX&Tel:+44 7922 908979）

**Comment by MrD-Lt** [comment]
Thank you, Leo. I'm currently interested in following Dr. Leung's research.
